In [22]:
import numpy as np
import pandas as pd
import re
import string
import pickle

In [23]:
txt = "Great product. i like it"

In [24]:
def remove_punctuations(text):
    for punctuations in string.punctuation:
        text=text.replace(punctuations,'')
    return text
        

In [25]:
vocab=pd.read_csv("../static/model/vocabulary.txt",header=None)
tokens = vocab[0].tolist()

In [26]:
with open("../static/model/model.pickle","rb") as f:
    model = pickle.load(f)

In [27]:
with open("../static/model/corpora/stopwords/english","r") as file:
    sw=file.read().splitlines()

In [28]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [29]:
def preprocessing(text):
    data=pd.DataFrame([text],columns=["tweet"])
    data["tweet"]=data["tweet"].apply(lambda x:" ".join(x.lower() for x in x.split()))
    data["tweet"]=data["tweet"].apply(lambda x:" ".join(re.sub(r'^https?:\/\/.*[\r\n]*','',x,flags=re.MULTILINE) for x in x.split()))
    data["tweet"]=data["tweet"].apply(remove_punctuations)
    data["tweet"]=data["tweet"].str.replace('\d+','',regex=True)
    data["tweet"]=data["tweet"].apply(lambda x:" ".join(x for x in x.split() if x not in sw))
    data["tweet"]=data["tweet"].apply(lambda x:" ".join(ps.stem(x) for x in x.split()))
    return data["tweet"]

In [30]:
preprocessed_txt=preprocessing(txt)

In [31]:
def vectorizer(ds,vocabulary):
    vectorized_lst=[]
    
    for sentence in ds:
        sentence_lst=np.zeros(len(vocabulary))
        
        for i in range(len(vocabulary)):
            if vocabulary[i] in sentence.split():
                sentence_lst[i]=1
                
        vectorized_lst.append(sentence_lst)
    
    vectorized_lst_new=np.asarray(vectorized_lst,dtype=np.float32)
    
    return vectorized_lst_new

In [32]:
vectorized_txt=vectorizer(preprocessed_txt,tokens)

In [33]:
model.predict(vectorized_txt)

array([1], dtype=int64)

In [34]:
txt="bad product. i hate it"
preprocessed_txt=preprocessing(txt)
vectorized_txt=vectorizer(preprocessed_txt,tokens)
prediction=model.predict(vectorized_txt)
prediction


array([1], dtype=int64)

In [38]:
txt="good"
preprocessed_txt=preprocessing(txt)
vectorized_txt=vectorizer(preprocessed_txt,tokens)
prediction=model.predict(vectorized_txt)
prediction


array([1], dtype=int64)

In [39]:
def get_prediction(vectorized_txt):
    prediction=model.predict(vectorized_txt)
    if prediction == 1:
        return 'negative'
    else:
        return 'positive'

In [42]:
txt="awesome"
preprocessed_txt=preprocessing(txt)
vectorized_txt=vectorizer(preprocessed_txt,tokens)
prediction=get_prediction(vectorized_txt)
prediction

'positive'